# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sudo apt-get update && \
    sudo apt-get install -y software-properties-common && \
    sudo add-apt-repository ppa:jonathonf/python-3.6 -y && \
    sudo apt-get update && \
    sudo apt-get install python3.6 -y && \
    pip install --user pipenv && \
    export PATH=$HOME/.local/bin:$PATH && \
    make env
  displayName: 'Set up environment'

- script: |
    export PATH=$HOME/.local/bin:$PATH && \
    make lint
  displayName: 'Linting'

- script: |
    export PATH=$HOME/.local/bin:$PATH && \
    make unit_test
  displayName: 'Unit testing'

- script: |
    export PATH=$HOME/.local/bin:$PATH && \
    make integration_test
  displayName: 'Integration testing'
